const validateDelete = async function(data){
    //Check if object has all keys
    try {
        for (const [key, value] of this.rules) {
            if (!Object.prototype.hasOwnProperty.call(data, key) && value.autoGenerated) {
                throw `ERROR: ${key} is required!`
            }
        }
    } catch (error) {
        console.log(error)
    }

    //Check Types
    try {
        for (const [key, value] of this.rules) {
            if (typeof (data[key]) != value.type && value.autoGenerated) {
                throw `ERROR: ${key} must be a ${value.type}!`
            }
        }
    } catch (error) {
        console.log(error)
    }
    return true
}

export default validateDelete
